# Generated by Django 6.0.5 on 2026-05-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('get_1_cn', models.IntegerField(default=0)),
                ('get_2_no', models.IntegerField(default=0)),
                ('get_3_se', models.IntegerField(default=0)),
                ('get_4_su', models.IntegerField(default=0)),
                ('get_5_so', models.IntegerField(default=0)),
                ('get_6_mb', models.IntegerField(default=0)),
                ('get_7_le', models.IntegerField(default=0)),
                ('get_8_oe', models.IntegerField(default=0)),
                ('rodovias', models.IntegerField(default=0)),
                ('sem_informacao_geo', models.IntegerField(default=0)),
                ('total_obitos_mapa', models.IntegerField(default=0)),
                ('populacao', models.IntegerField(default=0)),
                ('frota_total', models.IntegerField(default=0)),
                ('frota_motos', models.IntegerField(default=0)),
                ('total_obitos_painel', models.IntegerField(default=0)),
                ('obitos_pedestres', models.IntegerField(default=0)),
                ('obitos_ciclistas', models.IntegerField(default=0)),
                ('obitos_motociclistas', models.IntegerField(default=0)),
                ('obitos_automoveis', models.IntegerField(default=0)),
                ('obitos_nao_informados_modal', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ano', 'mes')},
            },
        ),
    ]
